import { useEffect, useMemo, useRef, useState } from "react";
import { assertSuccessful, contractAddress, chain, chainHex, explorerUrl, readCase, readClient, readVersion, terminal, walletChain, writeClient, type CaseRecord } from "./contract";
import { loadJournal, updateRecord, type JournalRecord } from "./journal";
import { deduped } from "./rpc";
import { executeWrite, type Progress } from "./transaction";
import { useProviders, useWallet, wallet } from "./wallet";

const blank: Progress = { phase: "IDLE" };
function journalSnapshot() { try { return { records: loadJournal(), error: "" }; } catch (cause) { return { records: [] as JournalRecord[], error: cause instanceof Error ? cause.message : "Journal storage is unavailable." }; } }
function hashText(text: string) { return crypto.subtle.digest("SHA-256", new TextEncoder().encode(text)).then((b) => [...new Uint8Array(b)].map((v) => v.toString(16).padStart(2, "0")).join("")); }
function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`; return JSON.stringify(value); }
function normalizedArgs(method: string, args: unknown[]) { return args.map((value, index) => (method === "create_rubric" && index === 2) || (method === "replace_rubric" && index === 1) || (method === "put_review" && index === 1) ? JSON.parse(String(value)) : typeof value === "bigint" ? value.toString() : typeof value === "string" && /^0x[0-9a-fA-F]{40}$/.test(value) ? value.toLowerCase() : value); }
type DimensionDraft = { id: string; min: number; max: number; anchors: Record<number, string> };
const initialDimensions: DimensionDraft[] = [{ id: "clarity", min: 0, max: 2, anchors: { 0: "Unclear", 1: "Partly clear", 2: "Clear and specific" } }];

export function App() {
  const initialJournal = useMemo(journalSnapshot, []);
  const providers = useProviders(); const session = useWallet();
  const [caseId, setCaseId] = useState("1"); const [record, setRecord] = useState<CaseRecord | null>(null);
  const [dimensions, setDimensions] = useState<DimensionDraft[]>(initialDimensions); const [reviews, setReviews] = useState<Record<string, { score: number; rationale: string }>>({});
  const [reviewer, setReviewer] = useState(""); const [progress, setProgress] = useState(blank); const [error, setError] = useState(initialJournal.error);
  const [journal, setJournal] = useState<JournalRecord[]>(initialJournal.records);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => wallet.providers(providers), [providers]);
  useEffect(() => { session.phase === "CHOOSER_OPEN" ? dialog.current?.showModal() : dialog.current?.close(); }, [session.phase]);
  const connected = session.phase === "CONNECTED" && session.account && session.selected;
  const canWrite = Boolean(connected && contractAddress && navigator.locks && !initialJournal.error && !["WAITING_FOR_WALLET", "SUBMITTED", "WAITING_FOR_FINALITY", "VERIFYING_EXECUTION", "VERIFYING_READBACK"].includes(progress.phase));
  const role = useMemo(() => !record || !session.account ? "reader" : record.primary === session.account ? "owner" : record.secondary === session.account ? "reviewer" : "evaluator", [record, session.account]);
  const rubric = useMemo(() => JSON.stringify({ dimensions: dimensions.map((item) => ({ id: item.id, min: item.min, max: item.max, anchors: Array.from({ length: item.max - item.min + 1 }, (_, offset) => ({ score: item.min + offset, text: item.anchors[item.min + offset] ?? "" })) })) }), [dimensions]);
  const review = useMemo(() => JSON.stringify({ reviews: (record?.base.dimensions ?? []).map((item) => ({ dimension_id: item.id, score: reviews[item.id]?.score ?? item.min, rationale: reviews[item.id]?.rationale ?? "" })) }), [record, reviews]);
  function showRecord(next: CaseRecord) { setRecord(next); setDimensions(next.base.dimensions.map((item) => ({ id: item.id, min: item.min, max: item.max, anchors: Object.fromEntries(item.anchors.map((anchor) => [anchor.score, anchor.text])) }))); setReviews(Object.fromEntries((next.response.reviews ?? []).map((item) => [item.dimension_id, { score: item.score, rationale: item.rationale }]))); }
  async function load() { setError(""); try { const next = await deduped("detail", `${chain.id}:${contractAddress}:get_case:${caseId}`, () => readCase(caseId)); next ? showRecord(next) : setRecord(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Read failed."); } }
  async function write(method: string, args: unknown[], intent: string, expectedPhase?: string) {
    if (!connected || !contractAddress) return;
    const address = contractAddress;
    const before = record; const preRevision = before?.revision ?? "0"; const preHash = await hashText(JSON.stringify(before));
    setError("");
    try {
      const client = writeClient(session.selected!.provider, session.account!);
      await executeWrite({ chain: String(chain.id), contract: address, account: session.account!, method, intent, args, preRevision, preHash,
        submit: () => client.writeContract({ address, functionName: method, args: args as never[], value: 0n }), progress: setProgress,
        verify: async () => { const id = method === "create_rubric" ? String(await client.readContract({ address, functionName: "get_id_by_nonce", args: [session.account!, args[0] as string] })) : caseId; const revision = method === "create_rubric" ? "1" : String(BigInt(preRevision) + 1n); const next = await readVersion(id, revision); if (!next) throw new Error("Expected historical revision was not found."); const argsHash = await hashText(canonical(normalizedArgs(method, args))); if (next.last_operation.method !== method || next.last_operation.caller !== session.account || next.last_operation.args_hash !== argsHash) throw new Error("Authoritative operation readback mismatch."); if (expectedPhase && next.phase !== expectedPhase) throw new Error("Phase readback mismatch."); setCaseId(next.id); showRecord(next); },
      });
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Write failed."); }
    finally { const snapshot = journalSnapshot(); setJournal(snapshot.records); if (snapshot.error) setError(snapshot.error); }
  }
  async function reconcile(item: JournalRecord) {
    if (!item.tx_hash) { setError("No transaction hash is available. Check wallet history; this attempt cannot be resubmitted automatically."); return; }
    setProgress({ phase: "VERIFYING_EXECUTION", hash: item.tx_hash }); setError("");
    try {
      const transaction = await readClient.getTransaction({ hash: item.tx_hash as never });
      if (!terminal(transaction)) { setProgress({ phase: "RECONCILIATION_REQUIRED", hash: item.tx_hash, message: "The exact transaction is not finalized yet." }); return; }
      assertSuccessful(transaction); setProgress({ phase: "VERIFYING_READBACK", hash: item.tx_hash });
      const args = JSON.parse(item.args_json) as unknown[]; const id = item.method === "create_rubric" ? String(await readClient.readContract({ address: item.contract as `0x${string}`, functionName: "get_id_by_nonce", args: [item.account as `0x${string}`, args[0] as string] })) : item.intent.split(":")[1]; const revision = item.method === "create_rubric" ? "1" : String(BigInt(item.pre_revision) + 1n); const next = await readVersion(id, revision);
      if (!next || next.last_operation.method !== item.method || next.last_operation.caller !== item.account || next.last_operation.args_hash !== await hashText(canonical(normalizedArgs(item.method, args)))) throw new Error("Authoritative historical readback mismatch.");
      await updateRecord(item.reservation, { status: "VERIFIED" }); showRecord(next); setCaseId(next.id); setProgress({ phase: "SUCCESS", hash: item.tx_hash }); setJournal(loadJournal());
    } catch (cause) { setProgress({ phase: "RECONCILIATION_REQUIRED", hash: item.tx_hash }); setError(cause instanceof Error ? cause.message : "Reconciliation failed."); }
  }
  function create() {
    const nonce = crypto.getRandomValues(new Uint8Array(16)).reduce((s, v) => s + v.toString(16).padStart(2, "0"), "");
    return write("create_rubric", [nonce, reviewer, rubric, 0n], `create:${session.account}:${nonce}`);
  }
  const active = progress.phase !== "IDLE";
  return <main>
    <header><div><span className="eyebrow">GenLayer calibration record</span><h1>Rubric Rationale Calibrator</h1></div>{connected ? <button onClick={() => wallet.disconnect()}>{session.selected!.name} · {session.account!.slice(0, 6)}…{session.account!.slice(-4)} · Disconnect</button> : session.phase === "WRONG_CHAIN" ? <button onClick={() => wallet.switchNetwork(walletChain)}>Switch network</button> : <button onClick={() => wallet.open()}>Connect wallet</button>}</header>
    <section className="hero"><h2>Does the written rationale actually support the score?</h2><p>Freeze integer anchors before review, then record an independent rationale-to-anchor consistency assessment. Submission quality and external facts are not verified.</p><div className="boundary">All submitted text is public and permanent. Do not include private information, credentials or personal records.</div></section>
    {!contractAddress && <p role="alert" className="notice">Read-only preview: configure <code>VITE_CONTRACT_ADDRESS</code> with this Task’s verified deployment before enabling chain actions.</p>}
    <section className="workspace"><aside><h2>Open a record</h2><label>Case ID<input value={caseId} onChange={(e) => setCaseId(e.target.value)} inputMode="numeric" /></label><button onClick={load} disabled={!contractAddress}>Load exact case</button><dl><dt>Wallet role</dt><dd>{role}</dd><dt>Phase</dt><dd>{record?.phase ?? "No case loaded"}</dd><dt>Revision</dt><dd>{record?.revision ?? "—"}</dd><dt>Outcome</dt><dd>{record?.outcome || "—"}</dd></dl></aside>
      <div className="actions"><h2>Role actions</h2><label>Assigned reviewer address<input name="reviewer" value={reviewer} onChange={(e) => setReviewer(e.target.value)} placeholder="0x…" autoComplete="off" /></label><fieldset><legend>Rubric dimensions and complete integer anchors</legend>{dimensions.map((item, dimensionIndex) => <div className="dimension" key={dimensionIndex}><label>Dimension ID<input name={`dimension-${dimensionIndex}`} value={item.id} onChange={(e) => setDimensions((all) => all.map((value, index) => index === dimensionIndex ? { ...value, id: e.target.value } : value))} /></label><div className="range"><label>Minimum<input type="number" min="-100" max="100" value={item.min} onChange={(e) => setDimensions((all) => all.map((value, index) => index === dimensionIndex ? { ...value, min: Number(e.target.value) } : value))} /></label><label>Maximum<input type="number" min="-100" max="100" value={item.max} onChange={(e) => setDimensions((all) => all.map((value, index) => index === dimensionIndex ? { ...value, max: Number(e.target.value) } : value))} /></label></div>{item.max >= item.min && item.max - item.min <= 10 && Array.from({ length: item.max - item.min + 1 }, (_, offset) => item.min + offset).map((score) => <label key={score}>Anchor {score}<input name={`anchor-${dimensionIndex}-${score}`} value={item.anchors[score] ?? ""} maxLength={96} onChange={(e) => setDimensions((all) => all.map((value, index) => index === dimensionIndex ? { ...value, anchors: { ...value.anchors, [score]: e.target.value } } : value))} /></label>)}{dimensions.length > 1 && <button className="secondary" onClick={() => setDimensions((all) => all.filter((_, index) => index !== dimensionIndex))}>Remove dimension</button>}</div>)}<button className="secondary" disabled={dimensions.length >= 4} onClick={() => setDimensions((all) => [...all, { id: "", min: 0, max: 2, anchors: {} }])}>Add dimension</button></fieldset><button disabled={!canWrite} onClick={create}>Create rubric</button>
      {record && <><button disabled={!canWrite || role !== "owner" || record.phase !== "BASE_DRAFT"} onClick={() => write("replace_rubric", [BigInt(caseId), rubric, BigInt(record.revision)], `replace_rubric:${caseId}:${record.revision}`, "BASE_DRAFT")}>Replace rubric</button><button disabled={!canWrite || role !== "owner" || record.phase !== "BASE_DRAFT"} onClick={() => write("lock_rubric", [BigInt(caseId), BigInt(record.revision)], `lock_rubric:${caseId}:${record.revision}`, "BASE_LOCKED")}>Lock rubric</button>
      <fieldset><legend>Reviewer scores and separate rationales</legend>{record.base.dimensions.map((item) => <div className="dimension" key={item.id}><label>{item.id} score<select value={reviews[item.id]?.score ?? item.min} onChange={(e) => setReviews((all) => ({ ...all, [item.id]: { score: Number(e.target.value), rationale: all[item.id]?.rationale ?? "" } }))}>{item.anchors.map((anchor) => <option key={anchor.score} value={anchor.score}>{anchor.score} — {anchor.text}</option>)}</select></label><label>{item.id} rationale<textarea rows={4} maxLength={768} value={reviews[item.id]?.rationale ?? ""} onChange={(e) => setReviews((all) => ({ ...all, [item.id]: { score: all[item.id]?.score ?? item.min, rationale: e.target.value } }))} /></label></div>)}</fieldset><button disabled={!canWrite || role !== "reviewer" || !["BASE_LOCKED", "RESPONSE_DRAFT"].includes(record.phase)} onClick={() => write("put_review", [BigInt(caseId), review, BigInt(record.revision)], `put_review:${caseId}:${record.revision}`, "RESPONSE_DRAFT")}>Save review</button><button disabled={!canWrite || role !== "reviewer" || record.phase !== "RESPONSE_DRAFT"} onClick={() => write("freeze_review", [BigInt(caseId), BigInt(record.revision)], `freeze_review:${caseId}:${record.revision}`, "FROZEN")}>Freeze review</button><button disabled={!canWrite || record.phase !== "FROZEN"} onClick={() => write("calibrate_review", [BigInt(caseId), BigInt(record.revision)], `calibrate_review:${caseId}:${record.revision}`)}>Calibrate rationale</button><button disabled={!canWrite || record.phase !== "UNRESOLVED"} onClick={() => write("retry_review", [BigInt(caseId), BigInt(record.revision)], `retry_review:${caseId}:${record.revision}`)}>Retry unresolved assessment</button></>}</div></section>
    {active && <section className="progress" data-transaction-phase={progress.phase} role={progress.phase === "FAILED" || progress.phase === "REJECTED" ? "alert" : "status"} aria-live="polite"><span className={["WAITING_FOR_WALLET", "SUBMITTED", "WAITING_FOR_FINALITY", "VERIFYING_EXECUTION", "VERIFYING_READBACK"].includes(progress.phase) ? "spinner" : "dot"} /><div><strong>{progress.phase.replaceAll("_", " ")}</strong>{progress.hash && <p className="hash"><code>{progress.hash}</code><button onClick={() => navigator.clipboard.writeText(progress.hash!)}>Copy hash</button>{explorerUrl && <a href={`${explorerUrl}/transactions/${progress.hash}`} target="_blank" rel="noreferrer">Open explorer</a>}</p>}<p>{progress.message}</p></div></section>}
    {error && <p role="alert" className="error">{error}</p>}
    <section id="docs"><h2>How it works</h2><ol><li>The rubric owner defines every integer anchor and locks the rubric.</li><li>The assigned reviewer submits one score and rationale per dimension, then freezes the review.</li><li>GenLayer validators independently classify rationale support for each selected anchor.</li><li>The contract stores calibrated, needs-revision, or unresolved state with exact revision history.</li></ol><p>Assessment of this exact submitted material only; not verification of external facts.</p></section>
    <section id="journal"><h2>Local transaction journal</h2><p>Latest four of {journal.length} records. Reconcile means: do not submit again until the exact transaction is checked.</p>{journal.slice(-4).reverse().map((item) => <article key={item.reservation}><strong>{item.method}</strong> · {item.status}<small>{item.tx_hash || "Awaiting wallet hash"}</small>{!["VERIFIED", "FINALIZED_ERROR"].includes(item.status) && <button disabled={item.chain !== String(chain.id) || item.contract !== contractAddress || item.account !== session.account} onClick={() => reconcile(item)}>Resume exact transaction</button>}</article>)}<button disabled={!journal.length} onClick={() => { const blob = new Blob([JSON.stringify(journal, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "genlayer-transaction-journal.json"; link.click(); URL.revokeObjectURL(link.href); }}>Export journal</button></section>
    <dialog ref={dialog} onCancel={(e) => { e.preventDefault(); wallet.close(); }}><h2>Select a detected wallet</h2>{providers.length === 0 ? <p>No supported wallet was detected.</p> : providers.map((option) => <button key={option.id} onClick={() => wallet.connect(option, chainHex)}>{option.name}</button>)}<button onClick={() => wallet.close()}>Cancel</button></dialog>
  </main>;
}
